CMEN/Controllers/MenuController.cs
using CMEN.Models;
using CMEN.sr_centralizador;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CMEN.Controllers
{
    public class MenuController : Controller
    {

        ws_cmenSoapClient servicio = new ws_cmenSoapClient();
        Credenciales credenciales = new Credenciales();
        
        public MenuController()
        {
            credenciales.username = Configuracion.UsuarioServicio;
            credenciales.password = Configuracion.PasswordServicio;

        }

        #region Vistas
        public ActionResult Inicio()
        {
            return View();
        }

        public ActionResult CierreCaja()
        {
            return View();
        }

        public ActionResult Productos()
        {
            return View();
        }

        public ActionResult Categoria()
        {
            return View();
        }
        public ActionResult Linea()
        {
            return View();
        }
        public ActionResult UnidadMedida()
        {
            return View();
        }
        #endregion

        #region CierreCaja
        [HttpPost]
        public ActionResult ListCierreCajaXLocalPaginado(CierreCajaRequest request)
        {
            Local local = new Local();
            List<AperturaCierreCaja> cierreCaja = new List<AperturaCierreCaja>();

            local.Idlocal = (string)Session["IdLocal"];
            if (local.Idlocal != "0")
            {
                cierreCaja = servicio.getAperturaxFecha(credenciales, local.Idlocal, request.FechaInicio, request.FechaFin).ToList();
            }

            return Json(cierreCaja, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult ListVentaXCierreCajaPaginado(string IdAperturaCierre)
        {
            AperturaCierreCaja cierreCaja = new AperturaCierreCaja();
            List<Orden_Pedido> ventas = new List<Orden_Pedido>();

           if(IdAperturaCierre != "0")
            {
                cierreCaja.IdAperturacierre = IdAperturaCierre;
                ventas = servicio.getOrden_Pedidos(cierreCaja).ToList();
            }
            
            return Json(ventas, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ListDetalleVentaPaginado(string IdVenta)
        {
            Orden_Pedido venta = new Orden_Pedido();
            List<Detalle_Orden_Pedido> detalleVenta = new List<Detalle_Orden_Pedido>();
            if(IdVenta != "0")
            {
                venta.Pedido_ID = IdVenta;
                detalleVenta = servicio.getDetalle_Orden_Pedidos(venta).ToList();
            }
            
            return Json(detalleVenta, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region General

        [HttpPost]
        public ActionResult CambiarLocal(string IdLocal)
        {
            Session["IdLocal"] = IdLocal;

            Result result = new Result();
            result.IsSuccess = true;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ListComboLinea()
        {
            Local local = new Local();
            List<Linea> linea = new List<Linea>();

            local.Idlocal = (string)Session["IdLocal"];
            if (local.Idlocal != "0")
            {
                linea = servicio.GetLineas(credenciales, local.Idlocal).Where(x => x.Estado == "ACTIVO").ToList();
            }

            return Json(linea, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ListComboCategoria(string IdLinea)
        {
            Linea linea = new Linea();
            List<Categoria> categoria = new List<Categoria>();

            linea.Linea_id = IdLinea;
            if (linea.Linea_id != "0")
            {
                categoria = servicio.GetCategorias(credenciales, linea.Linea_id).Where(x => x.Estado == "ACTIVO").ToList();
            }

            return Json(categoria, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ListComboUnidadMedida()
        {
            Local local = new Local();
            List<Unidad_Medida> unidadMedida = new List<Unidad_Medida>();

            local.Idlocal = (string)Session["IdLocal"];
            if (local.Idlocal != "0")
            {
                unidadMedida = servicio.GetUnidad_Medidas(credenciales, local.Idlocal).Where(x => x.Estado == "ACTIVO").ToList();
            }

            return Json(unidadMedida, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult ListComboDespacho()
        {
            Local local = new Local();
            List<Impresora> despacho = new List<Impresora>();

            local.Idlocal = (string)Session["IdLocal"];
            if (local.Idlocal != "0")
            {
                despacho = servicio.GetImpresoras(local.Idlocal).ToList();
            }

            return Json(despacho, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult ListComboInsumo()
        {
            Local local = new Local();
            List<Insumo> insumo = new List<Insumo>();

            local.Idlocal = (string)Session["IdLocal"];
            if (local.Idlocal != "0")
            {
                insumo = servicio.GetInsumos(local.Idlocal).Where(x => x.Estado_insumo == "ACTIVO").ToList();
            }

            return Json(insumo, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Productos

        [HttpPost]
        public ActionResult ListProductoPaginado()
        {
            Local local = new Local();
            List<Producto> producto = new List<Producto>();

            local.Idlocal = (string)Session["IdLocal"];
            if (local.Idlocal != "0")
            {
                producto = servicio.GetProductos(credenciales, local.Idlocal).ToList();
            }

            return Json(producto, JsonRequestBehavior.AllowGet);

        }

        
        [HttpPost]
        public ActionResult ListCategoria(string IdLinea)
        {
            Linea linea = new Linea();
            List<Categoria> categoria = new List<Categoria>();

            linea.Linea_id = IdLinea;
            if (linea.Linea_id != "0")
            {
                categoria = servicio.GetCategorias(credenciales, linea.Linea_id).ToList();
            }

            return Json(categoria, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SaveProducto(Producto request)
        {

            request.Moneda = "SOLES";
            request.Idlocal = (string)Session["IdLocal"];
            var response = request.Producto_id == "0" ? servicio.SetProducto(request) : servicio.UpdateProducto(request);

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Linea

        [HttpPost]
        public ActionResult ListLinea()
        {
            Local local = new Local();
            List<Linea> linea = new List<Linea>();

            local.Idlocal = (string)Session["IdLocal"];
            if (local.Idlocal != "0")
            {
                linea = servicio.GetLineas(credenciales, local.Idlocal).ToList();
            }

            return Json(linea, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult SaveLinea(Linea request)
        {

            request.Idlocal = (string)Session["IdLocal"];
            var respuesta = request.Linea_id == "0" ?
                servicio.SetLinea(request) :
                servicio.UpdateLinea(request);


            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Categoria
        [HttpPost]
        public ActionResult SaveCategoria(Categoria request)
        {

            var respuesta = request.Categoria_id == "0" ?
                servicio.SetCategoria(request) :
                servicio.UpdateCategoria(request);


            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }


        #endregion

        #region Unidad Medida
        [HttpPost]
        public ActionResult ListUnidadMedida()
        {
            Local local = new Local();
            List<Unidad_Medida> unidadMedida = new List<Unidad_Medida>();

            local.Idlocal = (string)Session["IdLocal"];
            if (local.Idlocal != "0")
            {
                unidadMedida = servicio.GetUnidad_Medidas(credenciales, local.Idlocal).ToList();
            }

            return Json(unidadMedida, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SaveUnidadMedida(Unidad_Medida request)
        {

            request.Idlocal = (string)Session["IdLocal"];
            var respuesta = request.Unidad_medida_id == "0" ?
                servicio.SetUnidadMedida(request) :
                servicio.UpdateUnidadMedida(request);

            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }
        #endregion

    }
}

CMEN/Views/Menu/Categoria.cshtml
@{
    ViewBag.Title = "Categoria";
    if (Session["IdUsuario"] == null)
    {
        Response.Redirect("~/Account/Login");
    }
}

@section beforeStyles
{
    <link href="~/Content/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />

}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Categoría</h6>
    </div>
    <div class="card-body">
        <div class="row mb-1 hide" id="botones">
            <div class="col-md-3">
                <div class="form-group">
                    <label for="cboLinea">Linea</label>
                    <select class="form-control select" id="cboLinea"></select>
                </div>
            </div>
            <div class="col-md-9 text-right">
                <div class="form-group mb-2 hidden-xs">
                    <label></label>
                </div>
                <div class="form-group">
                    <button type="button" id="btnRecargarCategoria" class="btn btn-md btn-primary shadow-sm mb-1 mb-sm-0 mb-md-0"><i class="fa fa-sync-alt"></i> Recargar</button>
                    <button type="button" id="btnAgregarCategoria" class="btn btn-md btn-primary shadow-sm mb-1 mb-sm-0 mb-md-0"><i class="fa fa-plus-circle"></i> Agregar</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered display nowrap" id="grillaCategoria" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th class="text-center">Nombre</th>
                                <th>Estado</th>
                                <th>Atualización</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog" id="ModalAgregarCategoria">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-primary" id="titleCategoria"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="txtIdCategoria" value="0" />
                <input type="hidden" id="txtIdCategoriaRef" value="" />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="txtCategoria">Nombre</label>
                            <input type="text" class="form-control text-uppercase" id="txtCategoria" value="" maxlength="50" />
                            <span class="text-error hide">Este campo es obligarorio</span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="cboLineaAgregar">Linea</label>
                            <select class="form-control select" id="cboLineaAgregar"></select>
                            <span class="text-error hide">Este campo es obligarorio</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="cboEstado">Estado</label>
                            <select class="form-control select" id="cboEstado">
                                <option value="0">Seleccione estado</option>
                                <option value="1">ACTIVO</option>
                                <option value="2">BAJA</option>
                            </select>
                            <span class="text-error hide">Este campo es obligarorio</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
                    <button type="button" id="btnGuardarCategoria" class="btn btn-primary"><i class="fa fa-save"></i> Guardar</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Content/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>

        var urlListLinea = '@Url.Action("ListComboLinea", "Menu")';
        var urlListCategoriaPaginado = '@Url.Action("ListCategoria", "Menu")';
        var urlSaveCategoria = '@Url.Action("SaveCategoria", "Menu")';

    </script>
    <script src="~/js/pages/Categoria.js"></script>

}

CMEN/Views/Menu/CierreCaja.cshtml
@{
    ViewBag.Title = "Cierre Caja";
    if (Session["IdUsuario"] == null)
    {
        Response.Redirect("~/Account/Login");
    }
}

@section beforeStyles
{
    <link href="~/Content/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Cierres de Caja</h6>
    </div>
    <div class="card-body">
        <div class="row mb-1 hide" id="botones">
            <div class="col-sm-6 col-md-3">
                <div class="form-group">
                    <label>Fecha Inicio:</label>
                    <div class="input-group date">
                        <input type="date" id="txtFechaInicio" class="form-control">
                        <div class="input-group-append pt-1">
                            <i class="fa fa-calendar-alt"></i>
                        </div>
                    </div>
                    <span class="text-error hide">Este campo es obligarorio</span>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="form-group">
                    <label>Fecha Fin:</label>
                    <div class="input-group date">
                        <input type="date" id="txtFechaFin" class="form-control">
                        <div class="input-group-append pt-1">
                            <i class="fa fa-calendar-alt"></i>
                        </div>
                    </div>
                    <span class="text-error hide">Este campo es obligarorio</span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group mb-2 hidden-xs">
                    <label></label>
                </div>
                <div class="form-group">
                    <button type="button" id="btnFiltrarXFecha" class="btn btn-md btn-primary shadow-sm mb-1 mb-sm-0 mb-md-0"><i class="fa fa-search"></i> Filtrar</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered display nowrap" id="grillaCierreCaja" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Hora Apertura</th>
                                <th>Monto Inicial</th>
                                <th>T. Efectivo</th>
                                <th>T. Compras</th>
                                <th>T. Pagos</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalVentasXCierreCaja" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-primary">Ventas</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" style="min-height:130px; padding-bottom:0px;">
                <input type="hidden" id="txtIdAperturaCierreCaja" value="0" />
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table id="grillaVentasXCierreCaja" class="table table-bordered" style="width:100%;margin-bottom:0;">
                                <thead>
                                    <tr>
                                        <th>Tipo Documento</th>
                                        <th>Nro Serie</th>
                                        <th>Cliente</th>
                                        <th>Personal</th>
                                        <th>Total</th>
                                        <th>Razon Social</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Salir</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalDetalleVenta" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-primary">Detalle Ventas</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" style="min-height:130px; padding-bottom:0px;">
                <input type="hidden" id="txtIdVenta" value="0" />
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table id="grillaDetalleVenta" class="table table-bordered" style="width:100%;margin-bottom:0;">
                                <thead>
                                    <tr>
                                        <th>Producto</th>
                                        <th>Cantidad</th>
                                        <th>Precio Unitario</th>
                                        <th>IGV</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Salir</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Content/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <script>

        var urlListCierreCajaXLocalPaginado = '@Url.Action("ListCierreCajaXLocalPaginado", "Menu")';
        var urlListVentaXCierreCajaPaginado = '@Url.Action("ListVentaXCierreCajaPaginado", "Menu")';
        var urlListDetalleVentaPaginado = '@Url.Action("ListDetalleVentaPaginado", "Menu")';

    </script>
    <script src="~/js/pages/CierreCaja.js"></script>

}

CMEN/Views/Menu/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
    if (Session["IdUsuario"] == null)
    {
        Response.Redirect("~/Account/Login");
    }
}
<h1>INICIO</h1>

CMEN/Views/Menu/Linea.cshtml
@{
    ViewBag.Title = "Linea";
    if (Session["IdUsuario"] == null)
    {
        Response.Redirect("~/Account/Login");
    }
}

@section beforeStyles
{
    <link href="~/Content/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />

}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Linea</h6>
    </div>
    <div class="card-body">
        <div class="row mb-3 hide" id="botones">
            <div class="col-md-12 text-right">
                <button type="button" id="btnRecargarLinea" class="btn btn-md btn-primary shadow-sm mb-1 mb-sm-0 mb-md-0"><i class="fa fa-sync-alt"></i> Recargar</button>
                <button type="button" id="btnAgregarLinea" class="btn btn-md btn-primary shadow-sm mb-1 mb-sm-0 mb-md-0"><i class="fa fa-plus-circle"></i> Agregar</button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered display nowrap" id="grillaLinea" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th class="text-center">Nombre</th>
                                <th>Estado</th>
                                <th>Actualización</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog" id="ModalAgregarLinea">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-primary" id="titleLinea"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="txtIdLinea" value="0" />
                <input type="hidden" id="txtIdLineaRef" value="" />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="txtLinea">Nombre</label>
                            <input type="text" class="form-control text-uppercase" id="txtLinea" value="" maxlength="50" />
                            <span class="text-error hide">Este campo es obligarorio</span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="cboEstado">Estado</label>
                            <select class="form-control select" id="cboEstado">
                                <option value="0">Seleccione estado</option>
                                <option value="1">ACTIVO</option>
                                <option value="2">BAJA</option>
                            </select>
                            <span class="text-error hide">Este campo es obligarorio</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
                    <button type="button" id="btnGuardarLinea" class="btn btn-primary"><i class="fa fa-save"></i> Guardar</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Content/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>

        var urlListLineaPaginado = '@Url.Action("ListLinea", "Menu")';
        var urlSaveLinea = '@Url.Action("SaveLinea", "Menu")';

    </script>
    <script src="~/js/pages/Linea.js"></script>

}

CMEN/Views/Menu/UnidadMedida.cshtml
@{
    ViewBag.Title = "Unidad Medida";
    if (Session["IdUsuario"] == null)
    {
        Response.Redirect("~/Account/Login");
    }
}

@section beforeStyles
{
    <link href="~/Content/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />

}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Unidad de Medida</h6>
    </div>
    <div class="card-body">
        <div class="row mb-3 hide" id="botones">
            <div class="col-md-12 text-right">
                <button type="button" id="btnRecargarUnidadMedida" class="btn btn-md btn-primary shadow-sm mb-1 mb-sm-0 mb-md-0"><i class="fa fa-sync-alt"></i> Recargar</button>
                <button type="button" id="btnAgregarUnidadMedida" class="btn btn-md btn-primary shadow-sm mb-1 mb-sm-0 mb-md-0"><i class="fa fa-plus-circle"></i> Agregar</button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered display nowrap" id="grillaUnidadMedida" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th class="text-center">Nombre</th>
                                <th>Estado</th>
                                <th>Actualización</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog" id="ModalAgregarUnidadMedida">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-primary" id="titleUnidadMedida"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="txtIdUnidadMedida" value="0" />
                <input type="hidden" id="txtIdUnidadMedidaRef" value="" />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="txtUnidadMedida">Nombre</label>
                            <input type="text" class="form-control text-uppercase" id="txtUnidadMedida" value="" maxlength="50" />
                            <span class="text-error hide">Este campo es obligarorio</span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="cboEstado">Estado</label>
                            <select class="form-control select" id="cboEstado">
                                <option value="0">Seleccione estado</option>
                                <option value="1">ACTIVO</option>
                                <option value="2">BAJA</option>
                            </select>
                            <span class="text-error hide">Este campo es obligarorio</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
                    <button type="button" id="btnGuardarUnidadMedida" class="btn btn-primary"><i class="fa fa-save"></i> Guardar</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Content/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>

        var urlListUnidadMedidaPaginado = '@Url.Action("ListUnidadMedida", "Menu")';
        var urlSaveUnidadMedida = '@Url.Action("SaveUnidadMedida", "Menu")';

    </script>
    <script src="~/js/pages/UnidadMedida.js"></script>

}